'use strict';

var grunt = require('grunt');

/*
  ======== A Handy Little Nodeunit Reference ========
  https://github.com/caolan/nodeunit

  Test methods:
    test.expect(numAssertions)
    test.done()
  Test assertions:
    test.ok(value, [message])
    test.equal(actual, expected, [message])
    test.notEqual(actual, expected, [message])
    test.deepEqual(actual, expected, [message])
    test.notDeepEqual(actual, expected, [message])
    test.strictEqual(actual, expected, [message])
    test.notStrictEqual(actual, expected, [message])
    test.throws(block, [error], [message])
    test.doesNotThrow(block, [error], [message])
    test.ifError(value)
*/

exports.raml_versions = {
  setUp: function(done) {
    // setup here if necessary
    done();
  },
  default_options: function(test) {
    test.expect(3);

    test.ok(grunt.file.isFile('tmp/docs/index.html'), 'file generated by raml2html should exist.');
    test.ok(grunt.file.isFile('tmp/docs/v0.7/api/index.html'), 'versioned copy of file should exist.');

    var actual = grunt.file.read('tmp/docs/v0.7/api/index.html');
    var expected = grunt.file.read('tmp/docs/index.html');

    // check that the file contents are the same
    test.equal(actual, expected, 'versioned copy should have exact same contents.');

    test.done();
  },
};
